### ISSUE TITLE
Onsite Todo

### ISSUE THREAD

**Issue by ghost** [arpg-sophisticated/ar-tu-do#123]
- [x] Merge log-stats and test

- [x] Rviz Capture with Point-Cloud

- [x] Test with WF2, Record Data and Videos

- [x] Take Videos and Pictures of Track and Tests (always)

- [x] Check Motor

- [x] Think about alternative track / Outdoor (Niklas)

- [x] Test with Chassis -> Chassis seems to make problems -> 1st place Lidar a little bit higher, analyse difference on testing with and without chassis on 4.25 m/s (rosbag)

- [x] Higher Speed Test -> 4.25 seems to be the maximum sane value, we need rework on breaking / max-speed

- [x] Test obstacle detection -> fail, rework

- [x] Final measure WF2

- [x] fix chassis problems (see above), maybe related to rework breaking #121

- [x] - race faster than 4.25 m/s (see rework breaking #121)

- [x] Final measure WF5

- [x] 30 Minute longtermtest of WF5

- [x] Estimate speed like this: 1. bring car to specific speed, 2. pkill log_stats, 3. take time of n rounds (10?) manually, 4. pkill logstats, 5. while driving observe the track the car takes and measure it afterwards 6. compare measurements with values distance and speed avg from telemetry file

- [x] add correction factor for speed

- [x] Save RQT Data for last and best configuration

- [x] Save final telemetry data

- [ ] Video with chassis

- [ ] Send all Data to Marcel

- [x] Need drill hole in lidar platform for lidar cage
